### ISSUE TITLE
gwdetchar-omega loops when requesting absent channel

### ISSUE THREAD

**Issue by tjma12** [gwdetchar/gwdetchar#150]
I've run into a bug where `gwdetchar-omega` will enter a loop and query NDS over and over again if the configuration includes a channel that doesn't exist in frames during that period.

For example, if you include the channel `H1:PSL-DIAG_BULLSEYE_PIT_OUT_DQ` and look at a time before it was installed and added to the frames, you'll get this prompt repeating:

```
Opening new connection ... connected
    [10.21.2.4] set ALLOW_DATA_ON_TAPE='False'
Checking channels list against NDS2 database... done
Downloading data: |                                                                          | 0/545.0 (  0%) ETA ?     
/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py:1041: NDSWarning: Low level daq error occured [13]: Requested data were not found.
  io_nds2.NDSWarning)
```

**Comment by alurban** [comment]
@tjma12, I'm not able to reproduce this error. I've done a test at CIT, LHO, and LLO where I made up a gobbledygook channel name (`L1:GDS-CALIB_STRAINasdkfjaslkdfj`) and ran with this in the configuration using the `gwpysoft-2.7` install. On all three clusters, when it comes time to process that channel, the call to `TimeSeriesDict.get()` fails as expected:

```
Attempting to access data from frames...
Reading L1_HOFT_C00 frames: |
L1:GDS-CALIB_STRAINasdkfjaslkdfj not found in frame table of contents
Failed to access data from frames, trying NDS...
Opening new connection to 10.21.2.4... connected
    [10.21.2.4] set ALLOW_DATA_ON_TAPE='False'
Checking channels list against NDS2 database... /home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py:1041: NDSWarning: unique NDS2 channel match not found for 'L1:GDS-CALIB_STRAINasdkfjaslkdfj'
  io_nds2.NDSWarning)
connected
    [nds.ligo.caltech.edu] set ALLOW_DATA_ON_TAPE='False'
Checking channels list against NDS2 database... /home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py:1041: NDSWarning: unique NDS2 channel match not found for 'L1:GDS-CALIB_STRAINasdkfjaslkdfj'
  io_nds2.NDSWarning)
Opening new connection to nds.ligo-la.caltech.edu... connected
    [nds.ligo-la.caltech.edu] set ALLOW_DATA_ON_TAPE='False'
Checking channels list against NDS2 database... /home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py:1041: NDSWarning: unique NDS2 channel match not found for 'L1:GDS-CALIB_STRAINasdkfjaslkdfj'
  io_nds2.NDSWarning)
Opening new connection to 10.21.2.4... connected
    [10.21.2.4] set ALLOW_DATA_ON_TAPE='True'
Checking channels list against NDS2 database... /home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py:1041: NDSWarning: unique NDS2 channel match not found for 'L1:GDS-CALIB_STRAINasdkfjaslkdfj'
  io_nds2.NDSWarning)
Opening new connection to nds.ligo.caltech.edu... connected
    [nds.ligo.caltech.edu] set ALLOW_DATA_ON_TAPE='True'
Checking channels list against NDS2 database... /home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py:1041: NDSWarning: unique NDS2 channel match not found for 'L1:GDS-CALIB_STRAINasdkfjaslkdfj'
  io_nds2.NDSWarning)
Opening new connection to nds.ligo-la.caltech.edu... connected
    [nds.ligo-la.caltech.edu] set ALLOW_DATA_ON_TAPE='True'
Checking channels list against NDS2 database... /home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py:1041: NDSWarning: unique NDS2 channel match not found for 'L1:GDS-CALIB_STRAINasdkfjaslkdfj'
  io_nds2.NDSWarning)
Traceback (most recent call last):
  File "/home/detchar/opt/gwpysoft-2.7/bin/gwdetchar-omega", line 317, in <module>
    verbose=args.verbose)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py", line 1261, in get
    allow_tape=allow_tape, verbose=verbose, **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py", line 1061, in fetch
    raise RuntimeError(err)
RuntimeError: Cannot find all relevant data on any known server.
```

Three separate NDS servers are queried, twice each, and then the script fails when it's not able to locate the channel, as intended.

I'm not sure what to make of this. Were you able to finish a full scan?
