### ISSUE TITLE
Trouble getting channel list with gwdetchar-lasso-correlation (

### ISSUE THREAD

**Issue by jrsmith02** [gwdetchar/gwdetchar#188]
Automatic channel list generation is not working. Duncan said, "There's an issue with the datafind server, which is pushing you through to nds2, which I suspect hasn't been rigorously tested
Can you post that issue to the gwdetchar repo issues." See my error below. 

I've been trying this myself but lasso seems to break when creating a channel list saying:

(gwpysoft-2.7) [jrsmith@ldas-pcdev1 lasso]$ gwdetchar-lasso-correlation -i L1 -P L1:DMT-SNSW_EFFECTIVE_RANGE_MPC.mean -a 0.2 -c 0.9 -O 2.0 -j 8 -J 8 1225339218 1225375218
/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
-- Loading primary channel data
Attempting to access data from frames...
Server returned code 404: Not Found404 Not Found

The server has not found anything matching the Request-URI.
Failed to access data from frames, trying NDS...
Opening new connection to nds... connected
    [nds] set ALLOW_DATA_ON_TAPE='False'
Checking channels list against NDS2 database... done
/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/io/nds2.py:120: UserWarning: Requested at least one minute trend, but start and stop GPS times are not multiples of 60. Times will be expanded outwards to compensate
  warnings.warn("Requested at least one minute trend, but "
Downloading data: |█████████████████████████████████████████████████▉| 36059.9296091/36060.0 (100%) ETA 00:00 
-- Removing outliers above 2.000000 sigma
-- Loading auxiliary channel data
Identified 2152447 channels
Attempting to access data from frames...
Traceback (most recent call last):
  File "/home/detchar/opt/gwpysoft-2.7/bin/gwdetchar-lasso-correlation", line 279, in <module>
    observatory=args.ifo[0], pad=0, **io_kw)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py", line 1247, in get
    **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py", line 1152, in find
    channellist = ChannelList.from_names(*clist)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/detector/channel.py", line 670, in from_names
    for name in cls._split_names(namestr):
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/detector/channel.py", line 679, in _split_names
    namestr = QUOTE_REGEX.sub('', namestr)
TypeError: expected string or buffer

**Comment by eagoetz** [comment]
Closing this issue as it 6+ years old and no further updates since then. Please update this issue if there is still an issue. Thanks
