### ISSUE TITLE
unable to use gwdetchar-omega on CIT

### ISSUE THREAD

**Issue by Chichisheep** [gwdetchar/gwdetchar#277]
Dear Omegascan developers:

I am one of the GW low-latency pipeline (SPIIR pipeline) developers and would like to try Omegascan on CIT to investigate interesting events. I am totally new to this and were following the document that I could find online https://wiki.ligo.org/DetChar/WdqScan. I tried the following command. It returned with an error below. I also got a page using that command https://ldas-jobs.ligo.caltech.edu/~qi.chu/wdq/L1_1236815182.0/# with no plots. I wonder if this is the best place to report problems to Omega scan and if there is a latest document for this tool. Thank you in advance. Looking forward to your reply!

[qi.chu@ldas-pcdev11 3det_lowmass]$ gwdetchar-omega -i L1 1236815182
/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/pkg_resources/__init__.py:1268: UserWarning: /home/qichu/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Creating L1 omega scan at GPS second 1236815182.0
Identified epoch as 'O3'
Parsing the following configuration files:
    /home/detchar/etc/omega/O3/L-L1_R-selected.ini
Output directory created as /home/qichu/public_html/wdq/L1_1236815182.0
Setting up HTML at /home/qichu/public_html/wdq/L1_1236815182.0/index.html
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Launching omega scans
Processing primary channel
    Reading primary: |████████████████████████████████████████████████████████████████████████████████████████████| 1/1 (100%) ETA 00:00 Traceback (most recent call last):
  File "/home/detchar/opt/gwpysoft-2.7/bin/gwdetchar-omega", line 184, in <module>
    nproc=args.nproc, verbose='    Reading primary: ')
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwdetchar/io/datafind.py", line 193, in get_data
    verbose=verbose, **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py", line 310, in read
    return timeseries_reader(cls, source, *args, **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/io/core.py", line 45, in read
    return io_read_multi(joiner, cls, source, *args, **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/io/mp.py", line 96, in read_multi
    nproc, _read_single_file, files, verbose=verbose, unit='files')
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/utils/mp.py", line 132, in multiprocess_with_queues
    return list(map(_inner, inputs))
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/utils/mp.py", line 119, in _inner
    return func(x)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/io/mp.py", line 81, in _read_single_file
    return fobj, io_read(cls, fobj, *args, **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/astropy/io/registry.py", line 531, in read
    data = reader(*args, **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/io/gwf/__init__.py", line 379, in read_
    return reader(*args, **kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/io/gwf/__init__.py", line 283, in read_timeseries
    return read_timeseriesdict(source, [channel], *args, **kwargs)[channel]
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/io/gwf/__init__.py", line 267, in read_timeseriesdict
    series_class=series_class, **kwargs),
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/io/gwf/framecpp.py", line 137, in read
    scaled=scaled, series_class=series_class),
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/io/gwf/framecpp.py", line 199, in read_gwf
    frame = stream.ReadFrameNSubset(this, 0)
  File "/home/spiir/opt/misc/lib64/python2.7/site-packages/LDAStools/frameCPP.py", line 3491, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, IFrameFStream, name)
  File "/home/spiir/opt/misc/lib64/python2.7/site-packages/LDAStools/frameCPP.py", line 71, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/home/spiir/opt/misc/lib64/python2.7/site-packages/LDAStools/frameCPP.py", line 66, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'

(gwpysoft-2.7) [qi.chu@ldas-pcdev11 3det_lowmass]$

**Comment by Chichisheep** [comment]
Hi,

I found the problem that I installed an older version of framecpp. Using the system framecpp, I got the plots in https://ldas-jobs.ligo.caltech.edu/~qichu/wdq/L1_1236815182.0/. I am still wondering if the github is the place for questions and bugs.

Thank you.

**Comment by alurban** [comment]
@Chichisheep, thank you for posting this issue, we very much appreciate feedback from users and GitHub is absolutely the right venue for questions, bug reports, and feature requests. In this case it looks like you were able to quickly determine the issue and fix it, and I'm very glad the omega scans are working for you now. I'll close this issue accordingly.

Note, if it helps, I can't say enough good things about conda -- if you're running on one of the LDG clusters (CIT / LHO / LLO) then you have access to an environment that maintains (amongst other things) the latest released version of `gwdetchar`. All you need to do is activate it via:

```bash
[]$ source /cvmfs/ligo-containers.opensciencegrid.org/lscsoft/conda/latest/etc/profile.d/conda.sh
[]$ conda activate ligo-py37
```

This will give you the environment with python-3.7, which I recommend using, but there are also environments with python-3.6 and 2.7. Full documentation of LIGO's conda environments can be found [**here**](https://docs.ligo.org/lscsoft/conda/) (requires `LIGO.ORG` credentials).
