### ISSUE TITLE
gwdetchar-scattering fails with gaps in frame data

### ISSUE THREAD

**Issue by lauranuttall** [gwdetchar/gwdetchar#37]
Tried to run the scattering code over some time at LHO on 22nd Sept when there are gaps in the data. Looks like nds can't resample on the fly. This is what I did with the error message:

gwdetchar-scattering 1158541217 1158567497 -i H1 -a H1:DMT-GRD_ISC_LOCK_NOMINAL:1 -c H1:GDS-CALIB_STRAIN -f H1_HOFT_C00 -j 4

/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/home/detchar/opt/gwpysoft-2.7/bin/gwdetchar-scattering", line 213, in <module>
    resample=128, frametype=args.frametype))
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/timeseries/core.py", line 1151, in get
    verbose=verbose, *_kwargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/utils/deps.py", line 80, in wrapper
    return func(_args, **kwargs)
TypeError: fetch() got an unexpected keyword argument 'resample'

**Comment by alurban** [comment]
This is fixed by #267.
