### ISSUE TITLE
Lasso unnecesarily requires frametype when using a custom TimeSeries file

### ISSUE THREAD

**Issue by wutmeownow** [gwdetchar/gwdetchar#412]
When running the Lasso algorithm with a custom TimeSeries file, a frametype is still required or else the following error is given: 
```
Traceback (most recent call last):
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39/bin/gwdetchar-lasso-correlation", line 10, in <module>
    sys.exit(main())
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-20220524/lib/python3.9/site-packages/gwdetchar/lasso/__main__.py", line 484, in main
    primary.split(':')[1]].format(ifo=args.ifo)
IndexError: list index out of range
```

A temporary solution is to give any string as the frametype, since the frametype argument is never used when the algorithm reads in a custom TimeSeries file. However, a permanent solution would be to simply add/change the if-else block so that a frametype is not needed if the primary_file argument is used. I anticipate solving this issue myself.

**Comment by eagoetz** [comment]
@wutmeownow I'm closing this issue since there hasn't been updates on it in nearly 3 years. If this is still a problem, please reopen and send more details about the file an example command line so that we can help you debug. Thanks!
