### ISSUE TITLE
Value error in Lasso

### ISSUE THREAD

**Issue by jrsmith02** [gwdetchar/gwdetchar#429]
I am getting the error "ValueError: Value must be a nonnegative integer or None" when running lasso. 
I think it's due to this line: 
packages/gwdetchar/lasso/__main__.py", line 643, in main
    set_option('max_colwidth', -1)

Full message. 

Traceback (most recent call last):
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn/bin/gwdetchar-lasso-correlation", line 10, in <module>
    sys.exit(main())
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-20230425/lib/python3.9/site-packages/gwdetchar/lasso/__main__.py", line 643, in main
    set_option('max_colwidth', -1)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-20230425/lib/python3.9/site-packages/pandas/_config/config.py", line 261, in __call__
    return self.__func__(*args, **kwds)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-20230425/lib/python3.9/site-packages/pandas/_config/config.py", line 160, in _set_option
    o.validator(v)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-20230425/lib/python3.9/site-packages/pandas/_config/config.py", line 882, in is_nonnegative_int
    raise ValueError(msg)
ValueError: Value must be a nonnegative integer or None

Full command is here: 

(igwn) [joshua.smith@ldas-pcdev6 4Hz-lasso-Apr28-short]$ nohup gwdetchar-lasso-correlation -i H1 -f Apr2023H1chans-short.txt -p H1:GDS-CALIB_STRAIN_CLEAN -P H1_HOFT_C00 -b 27 34 -T second -a 0.2 -O 2.0 -J 16 -j 16 1366715718 1366719018 &

Working directory: 

/home/joshua.smith/public_html/detchar/preO4/4Hz-lasso-Apr28-short

**Comment by andrew-lundgren** [comment]
I reproduced the error. Created pull request #430 which fixes it.

Output page:
https://ldas-jobs.ligo.caltech.edu/~andrew.lundgren/detchar/PreO4/lasso/test/

**Comment by marissawalker** [comment]
This should be fixed in the latest pull request that was just merged https://github.com/gwdetchar/gwdetchar/pull/422
