### ISSUE TITLE
wdq executable fails to work after pip installation

### ISSUE THREAD

**Issue by rpfisher** [gwdetchar/gwdetchar#66]
Setting up a new virtualenv with and without --system-site-packages, I encountered the following errors in trying to run the wdq executable from gwdetchar:

1. Can be solved by running pip install enum, so it's likely a "missing dependency".  Here is the full traceback:  
``` 
(gwdetchar_fork_Aug2_3) [rfisher@ldas-pcdev2 gwdetchar_fork]$ wdq
Traceback (most recent call last):
  File "/home/rfisher/opt/gwdetchar_fork_Aug2_3/bin/wdq", line 33, in <module>
    from gwdetchar import (cli, omega, const)
  File "/home/rfisher/opt/gwdetchar_fork_Aug2_3/lib/python2.7/site-packages/gwdetchar/omega/__init__.py", line 45, in <module>
    from .scan import *
  File "/home/rfisher/opt/gwdetchar_fork_Aug2_3/lib/python2.7/site-packages/gwdetchar/omega/scan.py", line 30, in <module>
    from gwpy.detector import (Channel, ChannelList)
  File "/home/rfisher/opt/gwdetchar_fork_Aug2_3/lib/python2.7/site-packages/gwpy/detector/__init__.py", line 29, in <module>
    from .channel import *
  File "/home/rfisher/opt/gwdetchar_fork_Aug2_3/lib/python2.7/site-packages/gwpy/detector/channel.py", line 36, in <module>
    from ..io import (datafind, nds2 as io_nds2)
  File "/home/rfisher/opt/gwdetchar_fork_Aug2_3/lib/python2.7/site-packages/gwpy/io/nds2.py", line 25, in <module>
    import enum
ImportError: No module named enum 
```
2. Next error: 
``` 
(gwdetchar_fork_Aug2_3) [rfisher@ldas-pcdev2 gwdetchar_fork]$ wdq --help
Traceback (most recent call last):
  File "/home/rfisher/opt/gwdetchar_fork_Aug2_3/bin/wdq", line 33, in <module>
    from gwdetchar import (cli, omega, const)
  File "/home/rfisher/opt/gwdetchar_fork_Aug2_3/lib/python2.7/site-packages/gwdetchar/omega/__init__.py", line 45, in <module>
    from .scan import *
  File "/home/rfisher/opt/gwdetchar_fork_Aug2_3/lib/python2.7/site-packages/gwdetchar/omega/scan.py", line 30, in <module>
    from gwpy.detector import (Channel, ChannelList)
  File "/home/rfisher/opt/gwdetchar_fork_Aug2_3/lib/python2.7/site-packages/gwpy/detector/__init__.py", line 29, in <module>
    from .channel import *
  File "/home/rfisher/opt/gwdetchar_fork_Aug2_3/lib/python2.7/site-packages/gwpy/detector/channel.py", line 36, in <module>
    from ..io import (datafind, nds2 as io_nds2)
  File "/home/rfisher/opt/gwdetchar_fork_Aug2_3/lib/python2.7/site-packages/gwpy/io/nds2.py", line 350, in <module>
    sample_rate=None, type=Nds2ChannelType.any(),
  File "/home/rfisher/opt/gwdetchar_fork_Aug2_3/lib/python2.7/site-packages/gwpy/io/nds2.py", line 69, in any
    return reduce(operator.or_, (x.value for x in cls))
TypeError: 'type' object is not iterable 
```

**Comment by duncanmmacleod** [comment]
@rpfisher, please post the full traceback, including the command/script you are running (with formatting)

**Comment by duncanmmacleod** [comment]
@rpfisher, please confirm which version of gwpy you have installed in this virtualenv?
